name:                advent-solutions
version:             0.1.0.0
github:              "letsbreelhere/advent2019"
license:             BSD3
author:              "Bree Elle Gardner"
maintainer:          "letsbreelhere@gmail.com"
copyright:           "2019 Bree Elle Gardner"

description: "AoC 2019 solutions"

dependencies:
- base >= 4.7 && < 5
- lens
- mtl
- vector
- containers
- text
- split
- safe
- linear

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - LambdaCase
source-dirs: app

executables:
  5:
    main:                5.hs
    dependencies:
    - advent-solutions
  8:
    main:                8.hs
    dependencies:
    - advent-solutions
  9:
    main:                9.hs
    dependencies:
    - advent-solutions
  10:
    main:                10.hs
    dependencies:
    - advent-solutions
  11:
    main:                11.hs
    dependencies:
    - advent-solutions
  12:
    main:                12.hs
    dependencies:
    - advent-solutions
